#!/usr/bin/env python

import os, sys

if __name__ == "__main__":
	# Compile gamelang to C
	ret= os.system("./debug/debug " + sys.argv[1])
	if ret != 0:
		sys.exit(1);

	# Compile C to binary
	ret= os.system(
		"gcc"
		" -Wall -Wextra -Werror" +
		" -Wno-unused-parameter" +
		" -Wno-unused-variable -Wno-unused-but-set-variable" +
		" temp.c -o out")

	if ret == 0:
		sys.exit(0)
	else:
		sys.exit(1);

