#!/usr/bin/env python
import os, sys

test_files= [
	"declarations.gl",
	"func_args.gl",
	"simple_structs.gl",
	"struct_composition.gl",
        "arithmetic.gl",
        "conditionals.gl",
        "loops.gl",
        "methods.gl",
        "extern.gl",
        "templates.gl",
        "sizeof.gl"
]

if __name__ == "__main__":
	log= []
	failure_count= 0
	for test in test_files:
                print(test)
		ret= os.system("./compiler ./tests/" + test)
		if ret == 0:
			log.append("  " + test)
		else:
			failure_count += 1
			log.append("* " + test)

	if failure_count == 0:
		print("*** All tests completed ***")
	else:
		print("*** FAILED TESTS (" + str(failure_count) + ") ***")

	for row in log:
		print(row)

